title: Wired Brain Coffee
logo: "/images/company-logo.png?raw=true"
description: >
  High quality. slow roasted, premium beans for a smooth balanced taste and rich armoa.
  <br><br>
  60 State Street
  Suite 800
  Boston, MA 02109
  <br><br>
  <a href="https://www.pluralsight.com">www.wiredbraincoffee.com</a>

theme: jekyll-theme-minimal
